INSERT INTO `tbl_entity_organization` (
  `id`,
  `friendly_url`,
  `name`,
  `description`,
  `image_id`,
  `enter_time`,
  `update_time`,
  `abn`,
  `account_id`,
  `place_id`,
  `keywords`,
  `logo_id`,
  `banner_id`,
  `address_additional_info`,
  `email`,
  `telephone`,
  `alternate_telephone`,
  `mobile`,
  `fax_number`,
  `website_url`,
  `content`,
  `status`,
  `hours_work`,
  `facebook_link`,
  `twitter_link`,
  `linkedin_link`,
  `youtube_link`,
  `blog_link`,
  `pinterest_link`,
  `googleplus_link`)
  SELECT
    Listing.id,
    Listing.friendly_url,
    Listing.title as name,
    Listing.description,
    Listing.image_id,
    Listing.entered as enter_time,
    Listing.updated as update_time,
    Listing.abn,
    Listing.account_id,
    tbl_entity_google_place.id as place_id,
    Listing.keywords,
    Listing.image_id as logo_id,
    Listing.banner_id,
    Listing.address2 as `address_additional_info`,
    Listing.email,
    Listing.phone as telephone,
    Listing.alternate_phone as alternate_telephone,
    Listing.mobile_phone as mobile,
    Listing.fax as fax_number,
    Listing.url as website_url,
    Listing.long_description as content,
    Listing.status,
    Listing.hours_work,
    Listing.facebook_link,
    Listing.twitter_link,
    Listing.linkedin_link,
    Listing.youtube_link,
    Listing.blog_link,
    Listing.pinterest_link,
    Listing.googleplus_link
  FROM Listing
    JOIN tbl_entity_google_place ON Listing.id = tbl_entity_google_place.listing_id
  WHERE tbl_entity_google_place.types = 'street_address'
        AND Listing.id NOT IN (SELECT tbl_entity_organization.id FROM tbl_entity_organization)
  GROUP BY Listing.id
  ORDER BY Listing.id
  Limit 1000;
