DROP TABLE IF EXISTS `tbl_entity_organization_2`;
CREATE TABLE `tbl_entity_organization_2` AS
SELECT 
Listing.id,
Listing.friendly_url,
Listing.title as name,
'' as alertnate_name,
Listing.description,
Listing.image_id,
Listing.entered as enter_time,
Listing.updated as update_time,
Listing.keywords,
Listing.account_id,
Listing.abn,
CONCAT(Listing.address,'\n',Listing.address2) as street_address,
Listing.postcode_suburb_id as suburb_id,
Listing.keywords,
Listing.email,
Listing.phone as telephone,
Listing.alternate_phone as alternate_telephone,
Listing.mobile_phone as mobile,
Listing.fax as fax_number,
Listing.image_id as logo_id,
Listing.banner_id,
Listing.url as website_url,
Listing.long_description as content,
Listing.status,
Listing.hours_work,
Listing.facebook_link,
Listing.twitter_link,
Listing.linkedin_link,
Listing.youtube_link,
Listing.blog_link,
Listing.pinterest_link,
Listing.googleplus_link
FROM Listing;

ALTER TABLE `tbl_entity_organization_2` ENGINE = MYISAM DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `tbl_entity_organization_2`
MODIFY `id` INT(11) AUTO_INCREMENT PRIMARY KEY,
MODIFY `friendly_url` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `name` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `alertnate_name` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `description` VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `enter_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFY `update_time` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFY `abn` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `street_address` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `keywords` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `email` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `telephone` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `alternate_telephone` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `mobile` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `fax_number` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `website_url` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `status` VARCHAR(5) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `facebook_link` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `twitter_link` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `linkedin_link` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `youtube_link` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `blog_link` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `pinterest_link` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
MODIFY `googleplus_link` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT "";

